### ISSUE TITLE
Automatic timeout

### ISSUE THREAD

**Issue by qaisjp** [kitfist0/ComposeFlashlight#3]
Hi, thanks for the app!

It would be great if the app had functionality to automatically turn off the flashlight after a specified duration (in minutes).

The use case I have is that I want to use my phone flashlight as a temporary bed lamp while reading a book, and set it to automatically turn off after 30m, so that it doesn't stay on forever if I fall asleep.

**Comment by kitfist0** [comment]
Hello @qaisjp 👋🏼
This feature has been added in the new release!

**Comment by kitfist0** [comment]
Hello @qaisjp 👋🏼
This feature has been added in the new release v0.9.4!

**Comment by qaisjp** [comment]
Wow, thank you!
